---
title: "gabra_subunit_analysis"
output: html_document
date: "2024-03-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Install biocmanager packages
if(!require("BiocManager")){install.packages("BiocManager")}
if(!require("clusterProfiler")){install.packages("clusterProfiler")}
if(!require("AnnotationDbi")){install.packages("AnnotationDbi")}
if(!require("org.Mm.eg.db")){install.packages("org.Mm.eg.db")}
if(!require("readxl")){install.packages("readxl")}
if(!require("gplots")){BiocManager::install("gplots")}
if(!require("stringr")){BiocManager::install("stringr")}
if(!require("enrichplot")){BiocManager::install("enrichplot")}
if(!require("viridis")){BiocManager::install("viridis")}
if(!require("ggplot2")){BiocManager::install("ggplot2")}
if(!require("pheatmap")){BiocManager::install("pheatmap")}
if(!require("RColorBrewer")){BiocManager::install("RColorBrewer")}
if(!require("EnhancedVolcano")){BiocManager::install('EnhancedVolcano')}
if(!require("xlsx")){BiocManager::install('xlsx')}
if(!require("tidyverse")){BiocManager::install('tidyverse')}

# import libraries
library(clusterProfiler)
library(org.Mm.eg.db)
library(AnnotationDbi)
library(readxl)
library(gplots)
library(ggupset)
library(VennDiagram)
library(stringr)
library(viridis)
library(enrichplot)
library(ggplot2)
library(pheatmap)
library(RColorBrewer)
library(EnhancedVolcano)
library(xlsx)
library(tidyverse)
```

```{r data}
pcutoff = 0.05
FCcutoff = 1.5

# WT ezrin data
EzrinData <- read.csv("./tables/10003_Ezrin-BioID-Quant-WT-CYTO-vs-EZR_011923.csv")
keep <- !is.na(rownames(Nlgn2Data))
EzrinData <- EzrinData[keep,]
EzrinData <- EzrinData[!(duplicated(EzrinData$Symbol)) & !(is.na(EzrinData$Symbol)),]
EzrinData$log2_WT_EZR_v_WT_CYT_FC <- ((abs(EzrinData$WT_EZR_v_WT_CYT_FC))/EzrinData$WT_EZR_v_WT_CYT_FC) * log(abs(EzrinData$WT_EZR_v_WT_CYT_pval), base = 2)
rownames(EzrinData) <- EzrinData$Symbol
EzrinData$Genes <- EzrinData$Symbol

# Astro Nlgn2 data
Nlgn2Data <- read_excel("./tables/Neuroligin2_astrocyte_BioID_RawData.xlsx", sheet = "Table 4 NL2_v_Turbo")
keep <- !is.na(rownames(Nlgn2Data))
Nlgn2Data <- Nlgn2Data[keep,]
Nlgn2Data <- Nlgn2Data[!(duplicated(Nlgn2Data$Genes)) & !(is.na(Nlgn2Data$Genes)),]
Nlgn2Data$log2_NL2_v_Turbo_FC <- ((abs(Nlgn2Data$NL2_v_Turbo_FC))/Nlgn2Data$NL2_v_Turbo_FC) * log(abs(Nlgn2Data$NL2_v_Turbo_Pval), base = 2)
rownames(Nlgn2Data) <- Nlgn2Data$Genes

# Lamp1 data
Lamp1Data <- read_excel("./tables/6116_SupplementalData_121922.xlsx", sheet = "Table 5 Lamp1_v_Cyto")
keep <- !is.na(rownames(Lamp1Data))
Lamp1Data <- Lamp1Data[keep,]
Lamp1Data <- Lamp1Data[!(duplicated(Lamp1Data$Genes)) & !(is.na(Lamp1Data$Genes)),]
Lamp1Data$log2_Lamp1_v_Cyto_FC <- ((abs(Lamp1Data$Lamp1_v_Cyto_FC))/Lamp1Data$Lamp1_v_Cyto_FC) * log(abs(Lamp1Data$Lamp1_v_Cyto_pval), base = 2)
rownames(Lamp1Data) <- Lamp1Data$Genes

# Split data
SplitData <- read_excel("./tables/Takano2020_Split-TurboID-Dataset_20221121.xlsx", sheet = "Split-TurboID")
keep <- !is.na(rownames(SplitData))
SplitData <- SplitData[keep,]
SplitData <- SplitData[!(duplicated(SplitData$Symbol)) & !(is.na(SplitData$Symbol)),]
SplitData$Split_v_Cyto_FC <- SplitData$`Fold enrichment` 
SplitData$log2_Split_v_Cyto_FC <- ((abs(SplitData$Split_v_Cyto_FC))/SplitData$Split_v_Cyto_FC) * log(abs(SplitData$'p-value'), base = 2)
rownames(SplitData) <- SplitData$Symbol
SplitData$Genes <- SplitData$Symbol

```

```{r load heatmap data}

# create matrix of per sample intensity data to feed into pheatmap() function
# adjust this code depending on your needs
library(tidyverse)

#merge data frames
heatmap_data <- list(EzrinData[c("Genes", "WT_EZR_v_WT_CYT_FC")], Nlgn2Data[c("Genes", "NL2_v_Turbo_FC")],  Lamp1Data[c("Genes", "Lamp1_v_Cyto_FC")], SplitData[c("Genes", "Split_v_Cyto_FC")])
heatmap_data <- Reduce(function(x, y) merge(x, y, all=TRUE), heatmap_data)  

#replace NAs with 0s
heatmap_data[is.na(heatmap_data)] <- 0
print(heatmap_data)

rownames(heatmap_data) <- heatmap_data$Genes
df_heatmap_samples <- as.data.frame(heatmap_data)

```

```{r cell-type marker genes from Soto et al., 2023 and/or from <https://www.abcam.com/neuroscience/neural-markers-guide>. Force undetected genes to 0}
gabaa_subunits <- Nlgn2Data$Genes[grep("Gabr", Nlgn2Data$Genes)]
gabaa_subunits <- append(gabaa_subunits, EzrinData$Genes[grep("Gabr", EzrinData$Genes)])
gabaa_subunits <- append(gabaa_subunits, Lamp1Data$Genes[grep("Gabr", Lamp1Data$Genes)])
gabaa_subunits <- gabaa_subunits[!duplicated(gabaa_subunits)]
print(gabaa_subunits)


#heatmap settings
#myheatcol <- grDevices::colorRampPalette(c("lightblue", "white", "orange"))(256)
annotation_row = data.frame(subunit_type = c("alpha", "alpha", "gamma", "alpha", "beta", "beta", "alpha", "delta", "beta"))
rownames(annotation_row) <- gabaa_subunits

toPlot_subunits <- as.data.frame(heatmap_data[heatmap_data$Genes %in% gabaa_subunits,])
colnames(toPlot_subunits) <- c("Genes", "Ezrin", "Nlgn2", "Lamp1", "Split")
rownames(toPlot_subunits) <- toPlot_subunits$Genes
toPlot_subunits <- subset(toPlot_subunits, select = c(2:5))

#set quantile break points <https://slowkow.com/notes/pheatmap-tutorial/>
quantile_breaks <- function(xs, n = 100) {
  breaks <- quantile(xs, probs = seq(0, 1, length.out = n))
  breaks[!duplicated(breaks)]
}

range <- c(min(toPlot_subunits[c(1:4)]), max(toPlot_subunits[c(1:4)]))
toPlot_subunits_breaks <- quantile_breaks(range, n = 101)

#reorder by annotation
toPlot_subunits_ordered <- toPlot_subunits[rownames(annotation_row), ]
toPlot_subunits_ordered <- toPlot_subunits_ordered[!(grepl("NA", rownames(toPlot_subunits_ordered))), ]

#plot heatmap
heatmap_subunits <- pheatmap(as.matrix(t(toPlot_subunits_ordered)), 
                             scale = "none", 
                             fontsize_row = 10, 
                             fontsize_col = 10, 
                             color = viridis(length(toPlot_subunits_breaks)),
                             #breaks = toPlot_subunits_breaks, 
                             angle_col = 315, 
                             main = "GABAAR subunits in astrocyte compartments", 
                             #annotation_col = annotation_row, 
                             cluster_cols = FALSE, cluster_rows = FALSE, 
                             cellheight = 15, cellwidth = 15)

heatmap_subunits

ppi <- 300
png(file = "./plots/heatmap_gabra_subunits.png", width = 11*ppi, height = 2*ppi, res = ppi)
  heatmap_subunits
dev.off()

```

```{r hit-lists}
# find hits >1.2 FC p < 0.05 between compartments
hits_downreg_GS <- GSData[GSData$GS_EZR_v_GS_CYT_FC <= -FCcutoff  & GSData$GS_EZR_v_GS_CYT_pval <= pcutoff,]$Symbol
hits_upreg_GS <- GSData[GSData$GS_EZR_v_GS_CYT_FC >= FCcutoff  & GSData$GS_EZR_v_GS_CYT_pval <= pcutoff,]$Symbol
hits_downreg_WT <- WTData[WTData$WT_EZR_v_WT_CYT_FC <= FCcutoff  & WTData$WT_EZR_v_WT_CYT_pval <= pcutoff,]$Symbol
hits_upreg_WT <- WTData[WTData$WT_EZR_v_WT_CYT_FC >= FCcutoff  & WTData$WT_EZR_v_WT_CYT_pval <= pcutoff,]$Symbol

#export csv files for Cytoscape
DEG_ezr_down <- data.frame(bait = "Ezrin",
                           interaction = "iBioID",
                           prey = hits_downreg_GSvsWT_EZR)
write.xlsx(DEG_ezr_down, file = "./cytoscape/cytoscape_network_GS_EZR_vs_WT_EZR_down.xlsx")

DEG_ezr_up <- data.frame(bait = "Ezrin",
                           interaction = "iBioID",
                           prey = hits_upreg_GSvsWT_EZR)
write.xlsx(DEG_ezr_up, file = "./cytoscape/cytoscape_network_GS_EZR_vs_WT_EZR_up.xlsx")

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
